#!/usr/bin/env python3
"""
Export to professional optical design formats
Zemax, OpticStudio, technical drawings
"""

from typing import Optional
import json

try:
    from .lens_editor import Lens
    from .optical_system import OpticalSystem
except (ImportError, ValueError):
    import sys
    import os
    sys.path.insert(0, os.path.dirname(__file__))
    from lens_editor import Lens
    from optical_system import OpticalSystem


class ZemaxExporter:
    """Export to Zemax format (.zmx)"""
    
    @staticmethod
    def export_lens(lens: Lens, filename: str):
        """Export single lens to Zemax format"""
        with open(filename, 'w') as f:
            f.write("! OpenLens Export\n")
            f.write(f"! {lens.name}\n")
            f.write("VERS 140000\n")
            f.write("MODE SEQ\n")
            f.write("\n")
            
            # Surface 0 (object)
            f.write("SURF 0\n")
            f.write("  TYPE STANDARD\n")
            f.write("  CURV 0.0\n")
            f.write("  DISZ INFINITY\n")
            f.write("\n")
            
            # Surface 1 (front)
            f.write("SURF 1\n")
            f.write("  TYPE STANDARD\n")
            f.write(f"  CURV {1/lens.radius_of_curvature_1 if lens.radius_of_curvature_1 != 0 else 0}\n")
            f.write(f"  DISZ {lens.thickness}\n")
            f.write(f"  DIAM {lens.diameter}\n")
            f.write(f"  GLAS {lens.material}\n")
            f.write("\n")
            
            # Surface 2 (back)
            f.write("SURF 2\n")
            f.write("  TYPE STANDARD\n")
            f.write(f"  CURV {1/lens.radius_of_curvature_2 if lens.radius_of_curvature_2 != 0 else 0}\n")
            f.write("  DISZ 100.0\n")
            f.write("\n")
            
            # Image surface
            f.write("SURF 3\n")
            f.write("  TYPE STANDARD\n")
            f.write("\n")


class PrescriptionExporter:
    """Export lens prescription format"""
    
    @staticmethod
    def export_prescription(lens: Lens, filename: str):
        """Export lens prescription (industry standard format)"""
        with open(filename, 'w') as f:
            f.write("LENS PRESCRIPTION\n")
            f.write("="*60 + "\n\n")
            f.write(f"Lens Name: {lens.name}\n")
            f.write(f"Lens Type: {lens.lens_type}\n\n")
            
            f.write("OPTICAL PARAMETERS:\n")
            f.write(f"  Radius of Curvature 1: {lens.radius_of_curvature_1:.3f} mm\n")
            f.write(f"  Radius of Curvature 2: {lens.radius_of_curvature_2:.3f} mm\n")
            f.write(f"  Center Thickness: {lens.thickness:.3f} mm\n")
            f.write(f"  Clear Aperture: {lens.diameter:.3f} mm\n")
            f.write(f"  Material: {lens.material}\n")
            f.write(f"  Refractive Index: {lens.refractive_index:.4f}\n")
            
            f_length = lens.calculate_focal_length()
            if f_length:
                f.write(f"  Focal Length: {f_length:.3f} mm\n")
            
            f.write("\n")
            f.write("Generated by OpenLens\n")

